version: '3.8'

services:
  pirlo:
    build: .
    container_name: pirlo 
    ports:
      - "10000:5000"
    volumes:
      # Codice dell’app per hot-reload in sviluppo
      - ./:/app
      # File di configurazione persistente
      - ../.global.env:/app/config/.global.env
      - ../:/host
      - /tmp/vm_pcaps/:/tmp/vm_pcaps/
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    environment:
      - "TZ=Europe/Rome"
      # Secret key per Flask (sostituisci in produzione)
      - SECRET_KEY=dev_secret_key
      # Per abilitare l’auto-reload di Flask in dev (opzionale)
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - HOST_IP=${HOST_IP}
      # Percorso chiave SSH host e cartella containers su host
      - SSH_KEY_PATH=/Users/simone/
      - CONTAINERS_HOST_PATH=/Users/simone/Desktop/Universita/CyberChallenge2025/AD_Infra_Kit

volumes:
  empty_volume:
